# csv of bank notes 400x400 pixel images
we are testing for bank notes to be forge or not

In [ ]:
import numpy as np
#generates array from text file
from numpy import genfromtxt

In [ ]:
data = genfromtxt('/content/drive/MyDrive/Udemy Computer Vision Course/DATA/bank_note_data.txt', delimiter=',')

In [ ]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [ ]:
labels = data[:,4]

In [ ]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [ ]:
features = data[:,0:4]

In [ ]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [ ]:
X = features
y = labels

In [ ]:
from sklearn.model_selection import train_test_split

# data split 

In [ ]:
#42 comes from Hitchhiker's guide to the galaxy
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

# data standardization

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler_object = MinMaxScaler()

In [ ]:
scaler_object.fit(X_train)

MinMaxScaler()

In [ ]:
scaled_X_train = scaler_object.transform(X_train)
scaled_X_test = scaler_object.transform(X_test)  

In [ ]:
X_train.max()

17.9274

In [ ]:
scaled_X_train.max()

1.0000000000000002

In [ ]:
X_test.max()

17.1116

In [ ]:
scaled_X_test.max()

1.02679563427227

# import keras

In [ ]:
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
model = Sequential()

In [ ]:
model.add(Dense(4,input_dim=4,activation='relu'))
model.add(Dense(8,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

#fit the model

In [ ]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [ ]:
model.fit(scaled_X_train,y_train,epochs=50,verbose=2)

In [ ]:
model.metrics_names

['loss', 'accuracy']

In [ ]:
model.evaluate(scaled_X_test,y_test)

15/15 [==============================] - 0s 2ms/step - loss: 0.2678 - accuracy: 0.9713


[0.26777780055999756, 0.9713024497032166]

In [ ]:
scaled_X_test

array([[0.62098955, 0.75284662, 0.21900753, 0.5730998 ],
       [0.48778602, 0.82175665, 0.09174727, 0.56211079],
       [0.51158363, 0.77924916, 0.13830875, 0.50392598],
       ...,
       [0.76115065, 0.62415668, 0.27251204, 0.83616757],
       [0.9047516 , 0.90329171, 0.03658247, 0.42267079],
       [0.49296526, 0.86039507, 0.06714046, 0.1622583 ]])

In [ ]:
#deprecated
#model.predict_classes(scaled_X_test)
(model.predict(scaled_X_test) > 0.5).astype("int32")

#confusion matrix

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

In [ ]:
predictions = (model.predict(scaled_X_test) > 0.5).astype("int32")

In [ ]:
confusion_matrix(y_test,predictions)

array([[256,   1],
       [ 12, 184]])

In [ ]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

         0.0       0.96      1.00      0.98       257
         1.0       0.99      0.94      0.97       196

    accuracy                           0.97       453
   macro avg       0.97      0.97      0.97       453
weighted avg       0.97      0.97      0.97       453



#save and load

In [ ]:
model.save('banknotemodel.h5')

In [ ]:
from keras.models import load_model

In [ ]:
load = load_model('banknotemodel.h5')