#iris dataset

In [1]:
import numpy as np

#data import

In [2]:
from sklearn import datasets
dataset = datasets.load_iris()

#assign & split X, y

In [17]:
#assigning X,y
X = dataset.data
y = dataset.target

In [5]:
#splitting data into train and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=None)

#SVM


In [6]:
#imports
from sklearn.svm import SVC

In [7]:
#model training
model = SVC(kernel='linear', C=1000)
model.fit(X_train, y_train)

SVC(C=1000, kernel='linear')

In [8]:
#train score
model.score(X_train, y_train)

1.0

In [9]:
#test score
model.score(X_test, y_test)

0.9333333333333333

In [10]:
model.predict(X_train)

array([1, 1, 0, 0, 1, 2, 2, 1, 2, 0, 0, 0, 2, 2, 0, 2, 0, 0, 1, 2, 0, 2,
       1, 0, 2, 0, 0, 2, 0, 1, 2, 2, 0, 0, 0, 0, 2, 1, 2, 0, 0, 0, 2, 1,
       1, 0, 2, 0, 1, 2, 1, 2, 1, 2, 0, 2, 0, 0, 1, 2, 0, 0, 0, 2, 1, 1,
       2, 2, 0, 0, 2, 1, 0, 1, 1, 2, 0, 1, 1, 2, 1, 2, 0, 1, 2, 2, 1, 2,
       1, 1, 2, 1, 2, 2, 1, 1, 0, 1, 1, 0, 2, 1, 0, 1, 0])

In [11]:
model.predict(X_test)

array([2, 0, 1, 2, 1, 2, 0, 0, 2, 1, 1, 2, 2, 1, 2, 2, 1, 2, 0, 1, 2, 2,
       0, 0, 0, 1, 2, 1, 1, 2, 1, 0, 0, 2, 1, 2, 0, 1, 1, 1, 0, 1, 2, 0,
       0])

#confusion matrix

In [12]:
expected = y_test
predicted = model.predict(X_test)

In [13]:
#confusion matrix
from sklearn import metrics
print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       0.94      0.88      0.91        17
           2       0.88      0.93      0.90        15

    accuracy                           0.93        45
   macro avg       0.94      0.94      0.94        45
weighted avg       0.93      0.93      0.93        45

[[13  0  0]
 [ 0 15  2]
 [ 0  1 14]]


#SVM Plot

In [14]:
#imports
from sklearn.svm import SVC
import numpy as np
import matplotlib.pyplot as plt

In [21]:
X = dataset.data[:, :2]
y = dataset.target

In [22]:
X.shape



(150, 2)

In [23]:
def SVMClassifier(kernel, cc, gamma):
  svc = SVC(kernel=kernel, C=cc, gamma=gamma)
  svc.fit(X, y)
  print(svc.score(X,y))
  h=0.02
  x_min, x_max = X[:, 0].min() - 1, X[:, 0].max() + 1
  y_min, y_max = X[:, 1].min() - 1, X[:, 0].max() + 1
  xx, yy = np.meshgrid(np.arange(x_min, x_max, h), np.arange(y_min, y_max, h))

  plt.subplot(1, 1, 1)
  Z = svc.predict(np.c_[xx.ravel(), yy.ravel()])
  Z = Z.reshape(xx.shape)
  plt.contourf(xx, yy, Z, cmap=plt.cm.Paired, alpha=0.8)
  plt.scatter(X[:, 0], X[:, 1], c=y)
  plt.xlabel('Sepal Length')
  plt.ylabel('Sepal Width')
  plt.xlim(xx.min(), xx.max())
  plt.show()

  #print('Training set accuracy %.2f' % svc.score(X[:, :2], y_train))
  #print('Test set accuracy %.2f' % svc.score(X_test[:, :2], y_test))


In [ ]:
from ipywidgets import interact
i = interact(SVMClassifier, kernel=({'linear', 'rbf'}), cc=(1.0, 10.0), gamma=(1.0, 10.0))